server:
  port: 7080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/playground
    username: testUser
    password: 1qazxsw2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

# パラメータの値をログに表示 ex.) binding parameter [1] as [INTEGER] - [1]
# logging.level.org.hibernate.type: trace にして出力されるログからパッケージを特定
# 2021-11-21 00:55:11.604 TRACE 11400 --- [ main] o.h.type.descriptor.sql.BasicBinder      : binding parameter [1] as [BIGINT] - [1]
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace


